@startuml

actor アクター

cloud GCP{
    rectangle CloudFunctions{
        usecase LINEbot
    }
}

cloud Twitter{
    usecase TwitterAPI
    rectangle Posts
}

アクター --> LINEbot :Tweetしたい内容
LINEbot --> TwitterAPI :Tweetしたい内容の受け渡し
TwitterAPI --> Posts :API経由でTweet

@enduml
