@startuml

actor アクター

cloud LINEbotAPI

cloud GCP{
    rectangle CloudFunctions{
        usecase ThisProgram
    }
}

cloud Twitter{
    usecase TwitterAPI
    rectangle Posts
}

アクター --> LINEbotAPI :Tweetしたい内容
LINEbotAPI --> ThisProgram :Tweetしたい内容をWEBhookで渡す
ThisProgram --> TwitterAPI :Tweetしたい内容をAPI経由で渡す
TwitterAPI --> Posts :API経由でTweet

@enduml
